### ISSUE TITLE
Bulk Processor Gets stuck on Certain Files

### ISSUE THREAD

**Issue by inkenbrandt** [utah-geological-survey/loggerloader#28]
`Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "llgui.py", line 291, in <lambda>
  File "llgui.py", line 470, in make_file_info_table
  File "loader.py", line 1430, in xle_head
  File "loader.py", line 983, in __init__
  File "loader.py", line 1257, in new_xle_imp
  File "pandas\core\tools\datetimes.py", line 808, in to_datetime
  File "pandas\core\tools\datetimes.py", line 908, in _assemble_from_unit_mappings
ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month,year] is missing
`
Add error handling for this line:         `f['DateTime'] = pd.to_datetime(f.apply(lambda x: x['Date'] + ' ' + x['Time'], 1))`

**Comment by inkenbrandt** [comment]
Issue happened on files without data.  Need to recognize files without data.
